### ISSUE TITLE
It doesn't save states of lists

### ISSUE THREAD

**Issue by AlekseyGor** [VladSavitsky/trellists#3]
It stopped remembering the current state of list visibility while switching between boards. Hide several lists. Then go to another board. Then come back and all lists are visible again. You have to configure it from the scratch. No good (

**Comment by VladSavitsky** [comment]
Hi! Thanks for very detailed bug description. I was able to reproduce it.
Will be fixed ASAP!

2016-03-09 15:56 GMT+02:00 AlekseyGor <notifications@github.com>:

> It stopped remembering the current state of list visibility while
> switching between boards. Hide several lists. Then go to another board.
> Then come back and all lists are visible again. You have to configure it
> from the scratch. No good (
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VladSavitsky/trellists/issues/3>.
>



-- 
Vlad Savitsky

+38096 530 27 12
Skype: vlad_savitsky
vlad.savitsky@gmail.com
http://www.linkedin.com/in/vladsavitsky

**Comment by VladSavitsky** [comment]
Fixed in version 2.6 and soon will be updated in your browser.
https://github.com/VladSavitsky/trellists/commit/b55a5a2139df23c42d8bdc963c7de0d0386835fe
