### ISSUE TITLE
The top menu disappears occasionally

### ISSUE THREAD

**Issue by UziTech** [VladSavitsky/trellists#5]
About half of the time the top menu bar disappears after the page finishes loading.

reloading the page a few times usually fixes it.

**Comment by ro6** [comment]
I'm having the same problem, but in my case the bar almost never stays visible, even after reloading several times. It seems like a race condition, maybe something loading after the Trellists menu and replacing it.

**Comment by gvilarino** [comment]
Same issue hear, in Chrome latest, today

**Comment by ziplock9000** [comment]
It's been happening for me in the last few weeks.
