### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by yueyericardo** [VladSavitsky/trellists#7]
https://chrome.google.com/webstore/detail/trellists-trello-lists-ma/dgnlcodfeenegnifnpcabcclldoceeml

I got Error 404 in chrome extension page, what happened?

**Comment by VladSavitsky** [comment]
Thanks for update.
Seems they remove it from store. Reasons:

> A justification for tabs is required. This can be entered on the Privacy tab.
> The single purpose description is required. This can be entered on the Privacy tab.

**Comment by VladSavitsky** [comment]
I did changes they want so extension soon will be published again. Sorry for delay.

**Comment by yueyericardo** [comment]
Thanks!

**Comment by fatihkisa** [comment]
> A justification for tabs is required. This can be entered on the Privacy tab.
> The single purpose description is required. This can be entered on the Privacy tab.

What did you do for these?
