### ISSUE TITLE
Extension link is 404

### ISSUE THREAD

**Issue by datazen** [VladSavitsky/trellists#8]
Love this extension however the link to Google Extensions to download is 404.

https://chrome.google.com/webstore/detail/trellists-trello-lists-ma/dgnlcodfeenegnifnpcabcclldoceeml

Any link I try from store is 404.    Any way you can fix this?   

Thank you.

**Comment by VladSavitsky** [comment]
Thank you. I already fixed problem and extension is on review. It's maybe 3rd or more attempt to pass their review. Hope this time I did everything right and extension will be published again. Usually review takes several days. Sorry but you need to wait. 

PS. Problem was in extra permissions which extension asked for but not used at all. Solution was to find which one and remove.
